### ISSUE TITLE
getVar() on bool

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xfguestbook#19]
When I try to install xfguestbook module with the latest Xoops 2.5.11; I get this error:

`Error: Error: Call to a member function getVar() on bool in file /class/libraries/vendor/xoops/xmf/src/Module/Helper/GenericHelper.php line 168`

Xoops core and module are in english.
___

My config:

PHP 7.4.7
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by mambax7** [comment]
Are you installing the [3.20_FINAL](https://github.com/XoopsModules25x/xfguestbook/releases/tag/3.20_FINAL) version?
Or the 3.21.0 Beta 2 ?

**Comment by mambax7** [comment]
This should fix it: https://github.com/XoopsModules25x/xfguestbook/pull/20

**Comment by cesagonchu** [comment]
Tyvm Mamba! Yes it was 3.21 Beta 2 and your modifications fixed it.
I have another issue:
https://github.com/XoopsModules25x/xfguestbook/issues/21
