### ISSUE TITLE
xoopsOption['template_main']

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xfguestbook#21]
When I want to "Create new entry" (user side)
modules/xfguestbook/xfcreate.php

I get this error:

`Warning: xoopsOption['template_main'] should be defined before including header.php in file /footer.php line 58`

and nothing is created/recorded.

**template_main** can be found here:

modules/xfguestbook/index.php
. Line 30: $GLOBALS['xoopsOption']['template_main'] = 'xfguestbook_index.tpl';

modules/xfguestbook/xfcreate.php
. Line 72: $GLOBALS['xoopsOption']['template_main'] = 'xfguestbook_signform.tpl';
Line 167: $GLOBALS['xoopsOption']['template_main'] = 'xfguestbook_signform.tpl';
Line 237: $GLOBALS['xoopsOption']['template_main'] = 'xfguestbook_signform.tpl';

___
My config:

PHP 7.4.7
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by mambax7** [comment]
This should fix it now: https://github.com/XoopsModules25x/xfguestbook/pull/22
