### ISSUE TITLE
Flags don't show

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/xfguestbook#23]
In older versions of the xfguestbook module, flags appeared in messages.

Example here:
http://www.gratilog.net/xoops/modules/xfguestbook/

Now they are no longer displayed and there are no error messages.

See here:
https://new.gratilog.net/xoops/modules/xfguestbook/

I tested with Xoops 2.5.11 beta1 in English and it's the same problem.

___
My config:

PHP 7.4.7
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by mambax7** [comment]
Should be fixed now in https://github.com/XoopsModules25x/xfguestbook/pull/24
